# -*- mode:org; mode:visual-line; -*-
#+TITLE: Optimal Control 1950-1985

#+BEGIN_COMMENT
An Org-mode template for building cosmoscopes using [[https://cosma.arthurperret.fr/user-manual.html#creating-content-text-files-markdown][cosma]].

Short of an extensive ox-backend, the initial Elisp source block
defines a few functions to export the current Org-mode buffer to a set
of Markdown files, formatted for cosma.

1. Prepare the configuration file ~config.yml~ in the same directory.

2. Prepare the Bibtex file (.bib) which needs conversion to the
[[https://citeproc-js.readthedocs.io/en/latest/csl-json/markup.html][CSL-JSON format]]. On the command line, this is done with:
~citeproc-js -i <bibfile> -o <jsonfile>~

3. Export the Org-mode buffer with the command `M-x jmc-md-files'.
The Org should follow these conventions:
  - Level 1 headlines are record titles
  - Level 1 headlines tags are cosma types
  - Level 1 headlines ~cosma-tags~ properties are cosma tags
  - Links exclusively used headline texts (not ids which are dynamically assigned)
  - Paragraph texts shoud be Markdown rather than Org

4. In a terminal/command windows, build the cosmoscope
~cosma modelize --citeproc~

#+END_COMMENT

#+BEGIN_SRC emacs-lisp :results silent

  (defvar cosma-zero-id 240000 "Start beyond 23:59:59 for id generation")
  (defconst cosma-yaml-template "---
      title: %s
      id: %s
      type: %s
      tags:
        - cosmoscope
      %s---

      "
    "Template for root node and yaml headers of individual .md files.")

  (defun jmc--cosma-newid ()
    "Generates a new unique id from the current day and incremented
      global counter."
    (setq cosma-zero-id (1+ cosma-zero-id))
    (let* ((now (decode-time (current-time)))
      	 (str (format "%6d" cosma-zero-id))
      	 (end (format "%2s%2s%2s" (substring str 0 2) (substring str 2 4) (substring str 4 6)))
      	 )
      (format "%04d%02d%02d%6s" (nth 5 now) (nth 4 now) (nth 3 now) end)))

  (defun jmc--cosma-collect-headlines (parsed)
    "Table of contents. Collects all level 1 headlines and assigns a unique id to each one,
      into an association list."
    (interactive)
    (let ((alist nil))
      (org-element-map parsed 'headline
        (lambda (hl)
      	(setq alist (append alist (list (cons (org-element-property :raw-value hl) (jmc--cosma-newid)))))))
      ;; (with-current-buffer (get-buffer-create "*TOC*")
      ;;   (insert (format "%s\n" alist)))
      alist))

  (defun jmc--cosma-links (str alist)
    "Search and replace links to headlines with links to ids in `str', using toc `alist'.

    Links are either `[[<headline>]]' or `[[<link-type>:<headline>]]', respectively replaced
  by `[[<uid>|<headline>]]' or `[[<link-type>:<uid>|<headline>]]'"
    (with-temp-buffer
      (erase-buffer)
      (insert str)
      (goto-char (point-min))
      (while (re-search-forward "\\[\\[\\([a-zA-Z0-9 \\.:]+\\)\\]\\]" nil t)
        (let* ((arr (save-match-data (split-string (match-string 1) ":")))
      	     (uid (if (= 1 (length arr))
      		      (assoc (match-string 1) alist)
      		    (assoc (cadr arr) alist))))
      	(if uid (replace-match
      		 (if (= 1 (length arr)) (format "%s|%s" (cdr uid) (car arr)) (format "%s:%s|%s" (car arr) (cdr uid) (cadr arr)))
      		 nil nil nil 1))
      	)
        )
      (buffer-string))
    )

  (defun jmc-cosma-setid ()
    (interactive)
    (org-set-property "CUSTOM_ID" (jmc--cosma-newid)))

  (defun jmc--cosma-get-config (key)
    (with-temp-buffer
      (erase-buffer)
      (insert-file "config.yml")
      (let* ((parsed (yaml-parse-string (buffer-string)))
  	   (val (gethash key parsed)))
        (when val
  	(set-text-properties 0 (length val) nil val)
  	val))))


  (defun jmc-md-files ()
    (interactive)
    (let* ((i 0)
  	 (files-origin (jmc--cosma-get-config 'files_origin))
      	 (parsed (org-element-parse-buffer))
      	 (toc (jmc--cosma-collect-headlines parsed))
      	 )
      ;; Export headline content as markdown file
      (org-element-map parsed 'headline
        (lambda (hl)
      	(with-current-buffer (get-buffer-create "*md-tmp*")
      	  (erase-buffer)
      	  (set-buffer-file-coding-system 'utf-8)
      	  (prefer-coding-system 'utf-8)
      	  (set-default-coding-systems 'utf-8)
      	  (set-language-environment 'utf-8)
      	  (set-selection-coding-system 'utf-8)
      	  (insert (if (org-element-property :CUSTOM_ID hl)
      		      (format "---\ntitle: %s\nid: %s\ntypes:\n"
      			      (org-element-property :raw-value hl)
      			      (org-element-property :CUSTOM_ID hl))
      		    (format "---\ntitle: %s\nid: %s\ntypes:\n"
      			    (org-element-property :raw-value hl)
      			    (cdr (assoc (org-element-property :raw-value hl) toc)))
      		    ))
  	;; Add Org-mode tags as cosma types. (Usually unique type.)
      	  (dolist (typ (org-element-property :tags hl))
      	    (insert (format "  - %s\n" typ)))
  	;; Tags if present
  	(let ((cosma-tags (cdr (assoc "COSMA-TAGS" (org-entry-properties hl)))))
  	  (when cosma-tags
  	    (insert "tags:\n")
  	    (dolist (tag (split-string cosma-tags " "))
  	      (insert (format "  - %s\n" tag)))))
      	  (insert "---\n\n"))

      	;; Fill content one paragraph at a time, skipping drawers
      	(org-element-map (org-element-contents hl) 'paragraph
      	  (lambda (para)
      	    (let ((str (buffer-substring-no-properties (org-element-property :contents-begin para)
      						       (org-element-property :contents-end para))))
      	      (with-current-buffer (get-buffer-create "*md-tmp*")
      		(insert (format "\n%s\n" (jmc--cosma-links str toc)))))))
      	;; Save file, hopefully with utf-8 encoding (see above)
      	(with-current-buffer (get-buffer-create "*md-tmp*")
      	  (write-file (format "%s\\OC_%d.md" files-origin i))
      	  (kill-buffer))
      	(setq i (1+ i))
      	))
      ))

#+END_SRC

* Optimal Control                                                     :maths:
Source for this cosmoscope: [@Bryson_1996].

Optimal control (OC) is one of several applications and extensions of the calculus of variations (CV). It deals with finding control time functions (histories) or control feedbackgains that minimize a performance index with differential equation consttraints. CV also deals with functions of more than one variable and is used to postulate variational principles in physics.

Herman H. Goldstine, a former assistant to [[contributeur:Gilbert A. Bliss]] at the University of Chicago, has written an excellent, scholarly history [@Goldstine_1980] of CV from its beginnings to the Chicago school in the early 20th century.

* Gilbert A. Bliss                                                   :person:
:PROPERTIES:
:cosma-tags: XXth Calculus-of-Variations
:END:
Gilbert Ames Bliss, (May, 9 1876 – May 8, 1951), was an American mathematician, known for his work on the calculus of variations, see also: [Wikipedia](https://en.wikipedia.org/wiki/Gilbert_Ames_Bliss).

## History

Goldstine suggests that the calculus of variations started with [[inventeur:Pierre de Fermat]] (1601-1665) when he postulated his principle that light travels through a sequence of optical media in minimum time (1662).

[[inventeur:Galileo Galilei]] (1564-1642) posed two problems in 1638 which were later solved by the calculus of variations:

- the "brachistochrone" problem of finding the shape of a wire such that a bead sliding along it traverses the distance between the two end points in minimum time, and
   
 - the shape assumed by a "heavy chain" hanging between two points.

However, Galileo's conjectures on the solutions were incorrect!

* Pierre de Fermat                                                   :person:
:PROPERTIES:
:cosma-tags: XVIIth optics
:END:
Pierre de Fermat (17 August 1601 – 12 January 1665) was a French magistrate, polymath, and above all, a mathematician who is given credit for early developments that led to infinitesimal calculus, including his technique of adequality. In particular, he is recognized for his discovery of an original method of finding the greatest and the smallest ordinates of curved lines, which is analogous to that of differential calculus, then unknown, and his research into number theory. He made notable contributions to analytic geometry, probability, and optics. He is best known for his Fermat's principle for light propagation and his Fermat's Last Theorem in number theory, which he described in a note at the margin of a copy of Diophantus' Arithmetica. He was also a lawyer at the parlement of Toulouse, France, a poet, a skilled Latinist, and a Hellenist, see also: [Wikipedia](https://en.wikipedia.org/wiki/Pierre_de_Fermat).

* Galileo Galilei                                                    :person:
:PROPERTIES:
:cosma-tags: XVIth XVIIth heliocentrism
:END:
Galileo di Vincenzo Bonaiuti de Galilei (15 February 1564 – 8 January 1642), commonly referred to as Galileo Galilei, was an Italian astronomer, physicist, and engineer, sometimes described as a polymath. He was born in the city of Pisa, then part of the Duchy of Florence. Galileo has been called the father of observational astronomy, modern-era classical physics, the scientific method, and modern science, see also [Wikipedia](https://en.wikipedia.org/wiki/Galileo_Galilei).
